---
title: "Age in Aberdeen"

output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(sf)
library(flexdashboard)
library(mapview)
library(gt)
library(cowplot)

theme_set(theme_cowplot())
```


```{r}
#load data and shapefiles 

age_all <- read_csv(here("data", "sape-2018-persons.csv"))

age_f <- read_csv(here("data", "sape-2018-females.csv"))

age_m <- read_csv(here("data", "sape-2018-males.csv"))

simd <- read_csv(here("data", "SIMD+2020v2+-+datazone+lookup.csv"))

datazone_sf <- st_read(here("data", "sc_dz_11.shp"), quiet = T)
```

```{r}
#new variables for age groups

age_all <- rename(age_all, age_90 = "age_90+")

age_all <-
  age_all %>%
  mutate(
    under_5 = rowSums(select(., age_0:age_4)), 
    perc_under_5 = round(under_5/total_population *100, 0),
    under_10 = rowSums(select(., age_0:age_9)), 
    perc_under_10 = round(under_10/total_population *100, 0),
    over_70 = rowSums(select(., age_70:age_90)),
    perc_over_70 = round(over_70/total_population * 100, 0),
    )
```

```{r}
# sum ages

council_ages <-
age_all %>%
  group_by(council_area) %>%
  summarise_at(vars(age_0:age_90), funs(sum))

long_council_ages <-
council_ages %>%
  pivot_longer(-council_area, names_to = "age", values_to = "population") %>%
  mutate(age = as.numeric(str_remove(age, "age_")))
  
  
# ggplot(data = filter(long_council_ages, council_area %in% c("Aberdeen City", "Aberdeenshire", "Moray"), age <90), aes(age, population)) + 
#   geom_line(aes(color = council_area), size = 2) +
#   scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
#   theme(legend.title = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), legend.position="bottom", plot.title = element_text(hjust = 0.5)) +
#   ggtitle("Age in Grampian Councils")
```



```{r}
#select Aberdeen City areas' data 
#join to shapefile

aberdeen_age_all <-
  age_all %>%
  filter(council_area == "Aberdeen City")

aberdeen_simd <-
  simd %>%
  filter(LAname == "Aberdeen City")

aberdeen <- 
  full_join(aberdeen_simd, aberdeen_age_all, by = c("DZ" = "data_zone"))

aberdeen_data_zones <- pull(aberdeen, DZ)

aberdeen_sf <- filter(datazone_sf, DataZone %in% aberdeen_data_zones)

aberdeen_sf <-
  merge(aberdeen_sf, aberdeen, by.x = "DataZone", by.y = "DZ")

```


Areas with high density people age 70+
=====================================

Row
-------------------------------------

###

```{r}
aberdeen_sf %>% 
  mapview(
    map.types = "OpenStreetMap", 
    zcol = "perc_over_70", 
    label = aberdeen_sf$Name,
    layer.name = "over 70 (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#table areas with highest fraction of population age 70 and over

aberdeen %>%
  select(DZ, IZname, total_population, perc_over_70, SIMD2020v2_Decile) %>%
  filter(perc_over_70 > 20) %>%
  arrange(SIMD2020v2_Decile) %>%
  gt() %>%
  tab_header(
    title = "Most Older People", 
    subtitle = "Areas with >20% of population age 70+, by most deprived") %>%
  cols_label(
    IZname = "Area", 
    total_population = "Population", 
    perc_over_70 = "age 70+ (%)",
    SIMD2020v2_Decile = "SIMD")  %>%
  tab_options(container.height = 400)
```



Areas with high density children under 10
=====================================

Row
-------------------------------------

###

```{r}
aberdeen_sf %>% 
  mapview(
    map.types = "OpenStreetMap", 
    zcol = "perc_under_10", 
    label = aberdeen_sf$Name,
    layer.name = "under 10 (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#table areas with highest fraction of population under age 10

aberdeen %>%
  select(DZ, IZname, total_population, perc_under_10, SIMD2020v2_Decile) %>%
  filter(perc_under_10 > 15) %>%
  arrange(SIMD2020v2_Decile) %>%
  gt() %>%
  tab_header(
    title = "Most Young Children", 
    subtitle = "Areas with >15% of population under 10, by most deprived") %>%
  cols_label(
    IZname = "Area", 
    total_population = "Population", 
    perc_under_10 = "under 10 (%)",
    SIMD2020v2_Decile = "SIMD")  %>%
  tab_options(container.height = 400)
```


Sources
=====================================

Row
-------------------------------------
###

2018 Small Area Population Estimates from National Records Scotland

Age data from https://www.nrscotland.gov.uk/statistics-and-data/statistics/statistics-by-theme/population/population-estimates/2011-based-special-area-population-estimates/small-area-population-estimates/time-series#2018

Scottish Index of Multiple Deprivation data from https://www.gov.scot/publications/scottish-index-of-multiple-deprivation-2020v2-data-zone-look-up/

Map shapefiles from https://data.gov.uk/dataset/ab9f1f20-3b7f-4efa-9bd2-239acf63b540/data-zone-boundaries-2011

Code at https://github.com/JessButler/age


